### ISSUE TITLE
Not an issue but i feel this class is incredibly weak on A20.

### ISSUE THREAD

**Issue by fkinghatesigningup** [JohnnyDevo/The-Mystic-Project#7]
I look at a lot of the upgraded cards and they look like worse versions of cards in the main classes (silent/defect/ironclad) like ebb and flow, fly, sideswipe, divining blow, bulk up, alacrity, arcane dodge.  Some cards might not even be strong without arcane/technical condition (flurry, mirror strike, vorpal thrust), admittedly most of them are and some are insane value (bladed dash, charged parry, floating disk, spell combat).

I feel like this class can only scale from cantrips but then probably gets destroyed on time eater.  

I'd like to discuss things like balance and power level but I'm not sure on an appropriate forum.  I feel bad because i mentioned how broken cantrip used to be and now the class feels unfun to play.

Suggestions: Add the following common card: Side-step: 2 cost, Gain 1(2) artifact. Exhaust. (Give the class some artifact to help it scale).  I'd like to hear how you feel about the class.

**Comment by NellyDevo** [comment]
Thanks for the feedback!

Yeah, I am aware of it being a bit weak. I'm collecting data on the mystic, and soon I'll have it assembled and I'll be able to make some informed balance decisions. I don't to blindly buff until I get the right thing and just end up with the exact reverse of the cantrips situation.

RE: side-step. I actually already have something that fills this design space in Obscuring Mist. It's purpose is exactly to provide artifact as a means of scaling with the collection of temp str/dex options the class has.

I don't really have my own channel or anything, but you can always reach me on reddit (u/Johnny_Devo), on Discord (JohnnyDevo#5188), and the slay the spire official discord has an "#unsupported-modding" channel that I hang out a lot in. Anyone is welcome there!

Anywho, I'm closing this issue because I probably shouldn't have this as a discussion forum.
